# Params bastion settings

- name: Create bastion group
  group:
    name: bastion
    state: present

- name: Create bastion user
  user:
    name: bastion
    comment: "bastion user"
    group: bastion

- name: Set gid on script command
  file:
    path: "{{ script_command_path }}"
    owner: root
    group: bastion
    mode: "g+s"

- name: Create bastion shell directory
  file:
    path: "{{ bastion_shell_path }}"
    owner: "{{ bastion_user }}"
    group: "{{ bastion_group }}"
    state: directory

- name: Create bastion log directory
  file:
    path: "{{ bastion_logs_directory }}"
    owner: bastion
    group: bastion
    mode: 0770
    recurse: yes
    state: directory

- name: Set file for log all command
  template:
    src: shell.j2
    dest: "{{ bastion_shell_path }}/shell"
    owner: root
    group: bastion
    mode: 0755

- name: Params sshd for log all commandes
  blockinfile:
    path: "{{ sshd_path }}"
    block: |
      Match User {{ bastion_users|join(',') }}
        ForceCommand /usr/bin/bastion/shell
        AllowTcpForwarding no
        X11Forwarding no
  notify: restart sshd

- name: Prevent users from viewing process ownerd by other users
  lineinfile:
    path: /etc/fstab
    regexp: '^proc '
    line: 'proc /proc proc defaults,hidepid=2 0 0'
  when: ansible_virtualization_type != "docker"
